

# qdrant
IMAGES_COLLECTION = "images"
IMAGES_VECTOR_DIM = 128
SEGMENTS_COLLECTION = "segments"
SEGMENTS_VECTOR_DIM = 512

# local file store
UPLOAD_DIR = "uploads"
COLLECTION_NAME = "images"
VECTOR_DIM_IMAGE = 128
VECTOR_DIM_SEGMENTS = 512